#!/usr/bin/env bash

# Copyright © 2016-2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
tty=$(tty)
pass=$(printf 'SETPROMPT Passphrase for pmount:\nGETPIN\n' | pinentry "--ttyname=$tty" | grep '^D ' | cut -c 3-)
pmount -p <(builtin printf '%s' "$pass") "$@"
