#!/usr/bin/env bash

# Copyright © 2016-2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
pass=$(SYSTEMD_COLORS=y systemd-ask-password 'Passphrase for pmount:')
pmount -p <(builtin printf '%s' "$pass") "$@"
